-- MySQL Script generated by MySQL Workbench
-- Thu May 28 13:53:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DiceProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DiceProject` ;

-- -----------------------------------------------------
-- Schema DiceProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiceProject` DEFAULT CHARACTER SET utf16 COLLATE utf16_bin ;
USE `DiceProject` ;

-- -----------------------------------------------------
-- Table `DiceProject`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`File` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`File` (
  `fileId` INT(32) UNSIGNED NOT NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `data` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`fileId`),
  UNIQUE INDEX `fileId_UNIQUE` (`fileId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


-- -----------------------------------------------------
-- Table `DiceProject`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`Project` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`Project` (
  `projectId` INT(32) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `researcherName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`projectId`),
  UNIQUE INDEX `groupId_UNIQUE` (`projectId` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


-- -----------------------------------------------------
-- Table `DiceProject`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`Role` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`Role` (
  `roleId` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(255) NULL,
  `information` VARCHAR(1023) NULL,
  PRIMARY KEY (`roleId`),
  UNIQUE INDEX `roleId_UNIQUE` (`roleId` ASC),
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


-- -----------------------------------------------------
-- Table `DiceProject`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`User` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`User` (
  `userId` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `addedBy` INT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


-- -----------------------------------------------------
-- Table `DiceProject`.`userFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`userFile` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`userFile` (
  `User_userId` INT(32) UNSIGNED NOT NULL,
  `File_fileId` INT(32) UNSIGNED NOT NULL,
  `property` INT(32) UNSIGNED NOT NULL,
  `isOwner` TINYINT(1) NULL,
  PRIMARY KEY (`User_userId`, `File_fileId`),
  INDEX `fk_userFile_User_idx` (`User_userId` ASC),
  INDEX `fk_userFile_File_idx` (`File_fileId` ASC),
  CONSTRAINT `fk_userFile_User`
    FOREIGN KEY (`User_userId`)
    REFERENCES `DiceProject`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userFile_File`
    FOREIGN KEY (`File_fileId`)
    REFERENCES `DiceProject`.`File` (`fileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


-- -----------------------------------------------------
-- Table `DiceProject`.`userRoleInGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiceProject`.`userRoleInGroup` ;

CREATE TABLE IF NOT EXISTS `DiceProject`.`userRoleInGroup` (
  `User_userId` INT(32) UNSIGNED NOT NULL,
  `Group_groupId` INT(32) NOT NULL,
  `Role_roleId` INT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`User_userId`, `Group_groupId`, `Role_roleId`),
  INDEX `fk_userRole_Group_idx` (`Group_groupId` ASC),
  INDEX `fk_userRole_User_idx` (`User_userId` ASC),
  INDEX `fk_userRole_Role_idx` (`Role_roleId` ASC),
  CONSTRAINT `fk_userRole_Group`
    FOREIGN KEY (`Group_groupId`)
    REFERENCES `DiceProject`.`Project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userRole_User`
    FOREIGN KEY (`User_userId`)
    REFERENCES `DiceProject`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userRole_Role`
    FOREIGN KEY (`Role_roleId`)
    REFERENCES `DiceProject`.`Role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
